// Login

export const LOGIN = {
  AUTH_GET: 'AUTH_GET',
  AUTH_GET_BY_TOKEN: 'AUTH_GET_BY_TOKEN',
  AUTH_REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  USER_INFO_GET: 'USER_INFO_GET',
  USER_SET: 'USER_SET',
  USER_ERROR: 'USER_ERROR',
  USER_CLEAR: 'USER_CLEAR'
} as const

// Gateway

export const GATEWAY = {
  GATEWAY_DATA_GET: 'GATEWAY_DATA_GET',
  GATEWAY_DATA_SET: 'GATEWAY_DATA_SET',
  GATEWAY_DATA_UPDATE_ITEM: 'GATEWAY_DATA_UPDATE_ITEM',
  GATEWAY_DATA_ERROR: 'GATEWAY_DATA_ERROR',
  GATEWAY_DATA_CLEAR: 'GATEWAY_DATA_CLEAR'
} as const
